[package]
name = "jazz-ml-vm"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
fnv     = "1.0.6"
rand    = "0.6.4"
colored = "1.7.0"
time = "0.1.42"
glfw = "0.26.1"

[profile.release]
lto   = true
panic = "abort"
